module.exports = {
  //Platforms
  PC: "https://api.paladins.com/paladinsapi.svc",

  //Response formats.
  JSON: "Json",
  XML: "Xml",

  //Language codes.
  ENGLISH: "1",
  GERMAN: "2",
  FRENCH: "3",
  SPANISH: "7",
  SPANISHLA: "9",
  PORTUGUESE: "10",
  RUSSIAN: "11",
  POLISH: "12",
  TURKISH: "13",

  ranks: {
    0:'Unranked', // Qualifying
    1:'Bronze_V',
    2:'Bronze_IV',
    3:'Bronze_III',
    4:'Bronze_II',
    5:'Bronze_I',
    6:'Silver_V',
    7:'Silver_IV',
    8:'Silver_III',
    9:'Silver_II',
    10:'Silver_I',
    11:'Gold_V',
    12:'Gold_IV',
    13:'Gold_III',
    14:'Gold_II',
    15:'Gold_I',
    16:'Platinum_V',
    17:'Platinum_IV',
    18:'Platinum_III',
    19:'Platinum_II',
    20:'Platinum_I',
    21:'Diamond_V',
    22:'Diamond_IV',
    23:'Diamond_III',
    24:'Diamond_II',
    25:'Diamond_I',
    26:'Master',
    27:'Grandmaster',
  },

  rankText: {
    'Unranked':0, // Qualifying
    'Bronze_V':1,
    'Bronze_IV':2,
    'Bronze_III':3,
    'Bronze_II':4,
    'Bronze_I':5,
    'Silver_V':6,
    'Silver_IV':7,
    'Silver_III':8,
    'Silver_II':9,
    'Silver_I':10,
    'Gold_V':11,
    'Gold_IV':12,
    'Gold_III':13,
    'Gold_II':14,
    'Gold_I':15,
    'Platinum_V':16,
    'Platinum_IV':17,
    'Platinum_III':18,
    'Platinum_II':19,
    'Platinum_I':20,
    'Diamond_V':21,
    'Diamond_IV':22,
    'Diamond_III':23,
    'Diamond_II':24,
    'Diamond_I':25,
    'Master':26,
    'Grandmaster':27
  }
};
